Repository P4P-Group129-2022/backend, pull requests merged in 2022-08, with the labels that each got.

#40 Implement git push endpoint
  src/controllers/GitActionsController.ts
  src/routes/GitActionsRoutes.ts
Labels: enhancement

#42 Implement git checkout and git branch endpoints
  .gitignore
  repos/scenarioDefaults/scenario-1/main.py
  repos/scenarioDefaults/test/main.py
  src/controllers/GitActionsController.ts
  src/controllers/ScenarioController.ts
  src/routes/GitActionsRoutes.ts
Labels: bug, enhancement

#44 Implement add remote
  src/controllers/GitActionsController.ts
  src/routes/GitActionsRoutes.ts
Labels: enhancement

#45 Changed the uri of the endpoint. Also changed the endpoint to check the user's correct repo.
  src/controllers/GitHubController.ts
  src/routes/GitHubRoutes.ts
Labels: enhancement

#47 Implement get all scenarios endpoint
  src/controllers/ScenarioController.ts
  src/routes/ScenarioRoutes.ts
Labels: enhancement

#48 Changed the gitdir path so that it is not OS dependent.
  src/controllers/GitActionsController.ts
Labels: enhancement

#49 Implement git rebase
  src/controllers/GitActionsController.ts
  src/routes/GitActionsRoutes.ts
Labels: enhancement

#53 Rearrange hierarchy of github endpoints
  src/routes/GitHubRoutes.ts
Labels: bug

#54 Add user endpoints
  src/controllers/UserController.ts
  src/models/User.ts
  src/routes/UserRoutes.ts
Labels: bug, enhancement

#55 Checkout to main when repo inits.
  src/controllers/GitActionsController.ts
Labels: enhancement
